### ISSUE TITLE
To do/Roadmap

### ISSUE THREAD

**Issue by Restioson** [Restioson/flower#74]
- [ ] Apic - assigned to @Gegy1000
- [ ] Better memory protections (preparation for userspace) - assigned to @Restioson #73
- [ ] HPET
- [ ] Acpi shutdown
- [ ] System calls
- [ ] Userspace & processes
- [ ] Process permissions system
- [ ] Multicore + scheduling
- [ ] IPC

**Comment by Restioson** [comment]
Better memory protections and preparation for userspace is done (#73).
